Vidly/Controllers/CustomersController.cs
using AutoMapper;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;


        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Customers
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            var viewModel = new NewCustomerViewModel()
            {
                MemberShipTypes = _context.MemberShipTypes,
                Customer = new Customer()
            };

            return View("CustomerForm", viewModel);
        }

        public ActionResult Details(int id)
        {
            if (id < 0)
                return HttpNotFound();

            var customer = _context.Customers.Include(x => x.MemberShipType).FirstOrDefault(x => x.Id == id);
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(NewCustomerViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                var newCustomer = new NewCustomerViewModel()
                {
                    Customer = viewModel.Customer,
                    MemberShipTypes = _context.MemberShipTypes
                };
                return View("CustomerForm", newCustomer);
            }


            if (viewModel.Customer.Id == 0)
                _context.Customers.Add(Mapper.Map<Customer>(viewModel));
            else
            {
                var customer = _context.Customers.Single(c => c.Id == viewModel.Customer.Id);
                Mapper.Map(viewModel, customer);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Edit(int id)
        {
            if (id < 0)
                return HttpNotFound();

            var customer = _context.Customers.Include(x => x.MemberShipType).SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();
            var viewModel = new NewCustomerViewModel()
            {
                Customer = customer,
                MemberShipTypes = _context.MemberShipTypes
            };

            return View("CustomerForm", viewModel);
        }
    }
}

Vidly/Controllers/MoviesController.cs
using AutoMapper;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;


namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            return View(_context.Movies.Include(x => x.Genre).ToList().ToList());
        }

        public ActionResult New()
        {
            var viewModel = new NewMovieViewModel()
            {
                Genres = _context.Genres
            };
            return View("MovieForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(NewMovieViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                var viewData = new NewMovieViewModel(viewModel)
                {
                    Genres = _context.Genres
                };
                return View("MovieForm", viewData);
            }

            if (viewModel.Id == 0)
            {
                var movie = Mapper.Map<Movie>(viewModel);
                movie.AddedDate = DateTime.Now;
                _context.Movies.Add(movie);
            }
            else
            {
                var movie = _context.Movies.Include(x => x.Genre).Single(x => x.Id == viewModel.Id);
                movie.AddedDate = DateTime.Now;
                Mapper.Map(viewModel, movie);
            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            if (id < 0)
                return HttpNotFound();

            var movie = _context.Movies.Include(m => m.Genre).FirstOrDefault(m => m.Id == id);
            return View(movie);
        }

        public ActionResult Edit(int id)
        {
            if (id < 0)
                return HttpNotFound();

            var movie = _context.Movies.Include(x => x.Genre).Single(x => x.Id == id);
            if (movie == null)
                return HttpNotFound();

            var movieViewModel = Mapper.Map<NewMovieViewModel>(movie);

            var viewModel = new NewMovieViewModel(movieViewModel)
            {
                Genres = _context.Genres
            };
            return View("MovieForm", viewModel);
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KCR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_Navbar.cshtml
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Movie", "Index", "Movies")</li>
                <li>@Html.ActionLink("Customer", "Index", "Customers")</li>
            </ul>
            @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>